### ISSUE TITLE
大佬请教下哦  请问user_   这后面如何随机成数字  是修改哪里呢？

### ISSUE THREAD

**Issue by Yakumo-Yukari** [journey-ad/chat-room#6]
我想在用户进入后随机用户名的时候user_ 123   使用这种形式 要修改那段代码呢？

**Comment by journey-ad** [comment]
这一行最后部分
https://github.com/journey-ad/chat-room/blob/18a3152656a5c53ca7fb3b295bd3f2a9085876ea/index.js#L34

**Comment by Yakumo-Yukari** [comment]
好的 谢谢了！！！
