### ISSUE TITLE
可任意修改消息或名字中的css

### ISSUE THREAD

**Issue by zqqqqz2000** [journey-ad/chat-room#8]
![Screen Shot 2022-02-20 at 7 18 04 PM](https://user-images.githubusercontent.com/31151349/154839922-0d9cfec4-6126-48d8-9734-6a2924044785.png)
可由此做到渲染过于复杂的页面导致浏览器卡死，或将元素fixed z-index: 9999，覆盖整个页面导致其他人无法发送消息，同时对老旧版本浏览器存在一定的安全风险
建议颜色选择处在服务器端过滤和验证颜色字符串

**Comment by journey-ad** [comment]
还真是👀，回头修一下
